# Stage 1 - Build the backend
FROM registry.access.redhat.com/ubi9/nodejs-24 AS backendBuilder

WORKDIR /opt/app-root/src
COPY /apps/backend/package*.json ./
USER root
RUN npm ci
COPY ./apps/backend ./
RUN npm run compile

# Stage 2 - Build the client
FROM registry.access.redhat.com/ubi9/nodejs-24 AS clientBuilder

WORKDIR /opt/app-root/src
USER root
RUN dnf install -y git && dnf clean all
COPY ./.git ./.git
RUN git config --global --add safe.directory /opt/app-root/src
COPY /apps/client/package*.json ./
RUN npm ci
COPY ./apps/client ./
RUN rm ./public/appConfig.json
RUN mv ./public/appConfig.docker.json ./public/appConfig.json
RUN npm run build

# Stage 3 - Build the admin
FROM registry.access.redhat.com/ubi9/nodejs-24 AS adminBuilder

WORKDIR /opt/app-root/src
COPY /apps/admin/package*.json ./
USER root
RUN npm ci
COPY ./apps/admin ./
RUN rm ./public/config.json
RUN mv ./public/config.docker.json ./public/config.json
RUN npm run build

# Stage 4 - Combine everything and run it
FROM registry.access.redhat.com/ubi9/nodejs-24

WORKDIR /opt/app-root/src
COPY /apps/backend/package*.json ./
USER root
RUN npm ci --production

COPY --from=backendBuilder /opt/app-root/src/dist ./
COPY /apps/backend/.env.example ./.env
COPY /apps/backend/App_Data ./App_Data_tmp
COPY /apps/backend/static ./static

COPY --from=clientBuilder /opt/app-root/src/build ./static/client
COPY --from=adminBuilder /opt/app-root/src/build ./static/admin

RUN chown -R 1001:0 ./App_Data_tmp && chmod -R g=u ./App_Data_tmp

EXPOSE 3002
USER 1001:0
CMD ["node", "index.js"]
